### ISSUE TITLE
recognise certificates

### ISSUE THREAD

**Issue by kandangit** [Notalib/nativescript-webview-ext#100]
### Which platform(s) does your issue occur on?
Have tested in Android 10, API Level 29
Android emulator Nexus 5X API 29

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.5.0
- nodejs: 10.15.0
- tns-core-modules: 6.5.18
- Runtime(s):
    "tns-android": {
      "version": "6.5.3"
     },
     "tns-ios": {
       "version": "6.5.3-rc.0"
     }
- Plugin(s): 6.5.3
Using the plugin within a NativeScript 6 app developed with Angular/TypeScript.

### Please, tell us how to recreate the issue in as much detail as possible.

Use the webview to display an external URL. In this URL some authentication occurs and at the end a landing page in another URL is displayed.

In the external URL, the third-party requests the certificate of the browser to log the user in.  The certificate is correctly installed but is not recognised by the third-party provider returning an authentication error.

When the URL is opened with an external browser within the emulator -outside the WebView- (i.e., Chrome), it works fine and is recognized. So it does not seem an issue with the installation of the certificate in the emulator.

**Does this plugin cover certificates or is not implemented?** 

If it was implemented have not see what should I do, otherwise would be nice to have it.

Thank you.

### Is there any code involved?
```
<nota:WebViewExt
     row="0"
     col="0"
     [src]="src"
     (loaded)="webviewLoaded($event)"
     debugMode="true"
     displayZoomControls="true"
     scrollBounce="false"
     supportZoom="false"
     viewPortSize="initial-scale=1.2"
 ></nota:WebViewExt>
```

**Comment by m-abs** [comment]
I must admit to be blank about how to solve this. I'd assume it would be enough to install the cert on the OS.

**Comment by kandangit** [comment]
I tested and this is also happening on NativeScript's built-in WebView.

As an alternative I am using InAppBrowser (Chrome Custom Tabs) plugin (https://www.npmjs.com/package/nativescript-inappbrowser) which does recognize the certificate. Clearly for some navigation to external URLs Chrome Custom Tabs seems better decision

I close then as it seem has not fix Thanks.

**Comment by kandangit** [comment]
I close as it seems it has not fix.
