### ISSUE TITLE
webview-ext not working nativescript-vue

### ISSUE THREAD

**Issue by leoincedo** [Notalib/nativescript-webview-ext#13]
i wanna use webview-ext with vuejs

but not working naitvesciprt-vue . :(

`CONSOLE ERROR file:///app/vendor.js:46260:20: [Vue warn]: Unknown custom element: <WebViewExt> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

thank you

**Comment by leoincedo** [comment]
i resolved it 

i was need this.

Vue.registerElement('WebViewExt', ()=> require('@nota/nativescript-webview-ext').WebViewExt)

thankyou~!

**Comment by m-abs** [comment]
Hi @leoincedo 
Thank you very much for the report and the solution.

I added it to the plugin.
If you update to `5.0.0-alpha.2` and import `@nota/nativescript-webview-ext/vue` in your app.js/main.js it should work.
