### ISSUE TITLE
How can I call NativeScript (Vue) function from WebView

### ISSUE THREAD

**Issue by meverikxp** [Notalib/nativescript-webview-ext#131]
I need call NativeScript (Vue) function from webview
Can you give me example for NativeScript Vue how I can do it? Thank you!

**Comment by m-abs** [comment]
You can't call NativeScript functions directly from the WebView.

But you can emit events from the WebView like this:

```javascript
window.nsWebViewBridge.emit("my-vue-event", { "hallo": "there" });
```

**Comment by meverikxp** [comment]
Yes, I did it, thank you
