### ISSUE TITLE
app crash after installing plugin with angular typescript

### ISSUE THREAD

**Issue by andrewvmail** [Notalib/nativescript-webview-ext#14]
After installing plugin on a fresh create tns app (angular) and then importing the module to NgModule import app keeps crashing on boot. have to remove plugin and tns platform  remove and tns platform add  ios again to get the app to boot again.

used
@nota/nativescript-webview-ext@5.0.0-alpha.2

**Comment by m-abs** [comment]
Hi @andrewvmail 

Thank you for the bug rapport.

I have been without a developer mac for the last week or so, so I haven't been able to verify this issue.
But I hope, I can have a look at this issue next week, so we can solve it.

We could use a few more details:
- iOS version
- xcode version
- tns runtime version

**Comment by andrewvmail** [comment]
I believe this is because Im using node 11.3. downgrading to latest 8 seems to be fine.
