### ISSUE TITLE
Scrolling not working on iOS 12.1.1

### ISSUE THREAD

**Issue by singhsaban** [Notalib/nativescript-webview-ext#16]
Hi,
The scrolling issue has re-appeared for iOS 12.1.1 #8 . 

I noticed that scrolling has been turned off in nativescript-webview-ext/webview-ext.uiwebview.js.

> uiWebView.scrollView.scrollEnabled = false;

And setting this to true does fix the issue. Let me know if this is a valid fix for the issue. I could send in a PR.

Thanks.

**Comment by m-abs** [comment]
Hmm, that's odd. 

UIWebview shouldn't be used on iOS 12.x.

**Comment by m-abs** [comment]
Could you provide an example project for this issue?

**Comment by singhsaban** [comment]
Hi @m-abs ,
I've created a demo nativescript-vue project https://github.com/singhsaban/webview-ext-demo. To replicate the issue on iOS 12.1.1 make the following true in the webview-ext package itself.

> uiWebView.scrollView.scrollEnabled = false;

**Comment by m-abs** [comment]
Hi thanks,

I've removed that line and fixed the test for UIWebView or WKWebView.
Only older versions of iOS should use UIWebView, but `12.1.1` resulted on a `NaN` so the check failed.

**Comment by singhsaban** [comment]
Thanks @m-abs for the fix.
