### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nnuvo** [Notalib/nativescript-webview-ext#17]
Plugin is crashing after tns install.
Vue, IOS 11.4 Emulator.

**Comment by m-abs** [comment]
Hi @nnuvo 

I'd really like to solve this issue, #14 reported something similar with angular but i can't reproduce it.

Could you provide an example project?

I'd also like to know which version of `xcode`, `tns-core-module`, `tns-ios` and `node` you're using.

**Comment by m-abs** [comment]
I'm closing this issue.

It might have caused by difference in xcode versions, this problem should be solved by 5.0.0.
