### ISSUE TITLE
cannot add plugin when using windows

### ISSUE THREAD

**Issue by stylefieber** [Notalib/nativescript-webview-ext#19]
When I try to add the plugin, following message appears:

npm ERR! @nota/nativescript-webview-ext@5.0.0 postinstall: `./make-podfile.sh`
npm ERR! Exit status 1

I guess it's because there is no bash on windows.

**Comment by m-abs** [comment]
Hi @stylefieber,

I've replaced the bash script with a javascript implementation, if you update to `5.0.2` you should be able to use the plugin on Windows.

**Comment by stylefieber** [comment]
Hi Morten!

thanks a lot! Will try it and provide feedback!

Am Di., 15. Jan. 2019 um 11:57 Uhr schrieb Morten Sjøgren <
notifications@github.com>:

**Comment by m-abs** [comment]
Hi @stylefieber 

I'm sorry, I must have forgotten to push the `5.0.2` to npmjs.
It has just been published.
