### ISSUE TITLE
scroll on ios 12.1.4

### ISSUE THREAD

**Issue by peppeg85** [Notalib/nativescript-webview-ext#23]
Hello, thanks for your update! 
i've installed it and now i can build on ios, but there is a strange behaviour: the webview doesn't scroll after been loaded.
when  i tap a link it is loaded externally with the browser and after i go back to the app it now scrolls...
on the viewloaded event i have this code to open the links in the browser:

`  
exports.viewLoaded = function (args) {

    var webView = args.object;
    if (webView.android) {
        webView.android.getSettings().setBuiltInZoomControls(false);
        webView.android.getSettings().setDisplayZoomControls(false);
    }

    webView.on(WebViewExt.shouldOverrideUrlLoadingEvent, (args) => {
        if (args.url != null && args.url.startsWith("https://")) {
            utilityModule.openUrl(args.url);
            return true;
        } else {
            return false;
        }
    })

 };
`

edit: i have:
 "tns-ios": {
      "version": "4.2.0"
    }

    "tns-core-modules": "^4.2.2"

**Comment by m-abs** [comment]
Hi @peppeg85 

We don't test for nativescript-4.x, is there some reason you're still on that version?

I don't see anything in your example that effects scrolling, can you provide a more complete example?

FYI. You can use `builtInZoomControls` and `displayZoomControls` from template, so you don't need to set those in code.
Also you need to put three "```" not just one to make a code-block, it makes it easier for me to read the code-block ;)

**Comment by m-abs** [comment]
Closed due to inactivity.
