### ISSUE TITLE
Javascript confirm() broken on iOS 

### ISSUE THREAD

**Issue by DanielDent** [Notalib/nativescript-webview-ext#29]
### Which platform(s) does your issue occur on?
- iOS
- Tested on emulator & iPhone 6

### Please, provide the following version numbers that your issue occurs with:
- CLI: 5.2.1
- iOS: XCode 10.2
- nodejs: v10.15.2
- tns-core-modules: 5.2.2
- Runtime(s): 5.0.0 / 5.0.0
- Plugin(s): no other plugins

### Please, tell us how to recreate the issue in as much detail as possible.
The `window.confirm()` and `confirm()` calls don't appear to work within a WebViewExt on iOS. On Android, `confirm()` appears to be handled by the underlying Chrome WebView.

The commit message for https://github.com/Notalib/nativescript-webview-ext/commit/c47a158ea4d825d0f3c81e9b240546b83a6712a4 seems to indicate that `confirm()` should be working on iOS WkWebView

### Is there any code involved?
I've created a simple example at https://github.com/DanielDent/webviewext-confirm-test. It's the vue-cli-template + a simple WebViewExt added in a second commit (https://github.com/DanielDent/webviewext-confirm-test/commit/1a6b0e199fef2b6967a6106cb5bb7dd0707f9e9b).

It works on Android, but does not work on iOS.

**Comment by m-abs** [comment]
Hi @DanielDent 

Thank you for your bug rapport.

I thinks this is a case of poor documentation and a choice to keep default behavior.

- `WKWebView` won't show `alert`, `confirm` and `prompt` boxes inside the webview, so they need to be handled by the native layer or they will be ignored.
- `UIWebView` supports `alert`, `confirm` and `prompt` boxes and cannot be overridden.
- `Android WebView` supports `alert`, `confirm` and `prompt` boxes, but they can be overridden.

You can use the events `WebViewExt.webAlertEvent`, `WebViewExt.webConfirmEvent` and `WebViewExt.webPromptEvent` to show your own `alert`, `confirm` and `prompt` boxes.
Or you can wait for my PR to be finished :) 
It will use `NativeScript`'s dialogs on `WKWebView`, if no event handler is defined.

**Comment by DanielDent** [comment]
Thanks for clarifying how things currently work. I'm looking forward to the completed PR :).
