### ISSUE TITLE
Add option to disable setting the viewport on WKWebView

### ISSUE THREAD

**Issue by ad1217** [Notalib/nativescript-webview-ext#32]
### Which platform(s) does your issue occur on?

- iOS 12
- tested in emulator, iPad, and iPhone

### Please, provide the following version numbers that your issue occurs with:

- CLI: 5.3.1
- iOS: XCode 10.1
- nodejs: v11.13.0
- tns-core-modules: 5.3.1
- Runtime(s): 5.2.0
- Plugin(s): N/A

### Please, tell us how to recreate the issue in as much detail as possible.
Setting/overriding the viewport, which is currently done by automatically injecting `metadata-view-port.js` when using a WKWebView, breaks the display of some sites. Unfortunately, I cannot give a specific example since the site I am testing requires authentication. It would be very helpful if this plugin provided an option to disable this behavior. 

Currently, we are disabling this feature with the following patch:
```patch
diff --git a/node_modules/@nota/nativescript-webview-ext/webview-ext.wkwebview.js b/node_modules/@nota/nativescript-webview-ext/webview-ext.wkwebview.js
index d30bd69..9d4a856 100644
--- a/node_modules/@nota/nativescript-webview-ext/webview-ext.wkwebview.js
+++ b/node_modules/@nota/nativescript-webview-ext/webview-ext.wkwebview.js
@@ -419,12 +419,7 @@ var WKWebViewWrapper = (function () {
     WKWebViewWrapper.prototype.loadWKUserScripts = function (autoInjectJSBridge) {
         if (autoInjectJSBridge === void 0) { autoInjectJSBridge = this.autoInjectJSBridge; }
         var e_1, _a;
-        if (!this.wkUserScriptViewPortCode) {
-            this.wkUserScriptViewPortCode = this.makeWKUserScriptPromise(nativescript_webview_bridge_loader_1.metadataViewPort);
-        }
         this.wkUserContentController.removeAllUserScripts();
-        var wkUserScriptViewPortCode = this.wkUserScriptViewPortCode;
-        this.addUserScriptFromPromise(wkUserScriptViewPortCode);
         if (!autoInjectJSBridge) {
             return;
         }
```

**Comment by m-abs** [comment]
I agree it should be optional.

This behavior was inherited from the upstream webview in `tns-core-modules`: https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/web-view/web-view.ios.ts#L101-L104

Alternatively we could check, if the web page already have viewport metadata?
Do you think that would for you?

**Comment by ad1217** [comment]
In this particular instance, it wouldn't. The site in question does not have a viewport set, and breaks when one is set.

**Comment by m-abs** [comment]
@ad1217 
This have been added to `v5.2.0`.

If you set `webview.viewPortSize = false` injecting the viewport size is disabled on `WkWebView`.
