### ISSUE TITLE
unable to run demo on Android

### ISSUE THREAD

**Issue by enfralys** [Notalib/nativescript-webview-ext#34]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- Android versions
- emulator or device. What type of device?
Device S8+

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
5.3.2

- nodejs: (run `node --version` to fetch it)
10.5.3
- tns-core-modules: (run `npm ls tns-core-modules` in your project to fetch it.)

- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
{
  "nativescript": {
    "name": "hugo",
    "id": "dk.nota.webviewdemo",
    "tns-android": {
      "version": "5.3.1"
    }
  },
  "dependencies": {
    "@nota/nativescript-webview-ext": "^5.1.2",
    "lodash": "^4.17.11",
    "nativescript-theme-core": "^1.0.4",
    "tns-core-modules": "~5.3.2",
    "url": "^0.11.0"
  },
  "devDependencies": {
    "@types/lodash": "^4.14.123",
    "ajv": "6.9.2",
    "http-server": "^0.11.1",
    "nativescript-dev-typescript": "~0.9.0",
    "nativescript-dev-webpack": "~0.21.2",
    "prettier": "^1.17.0",
    "tns-platform-declarations": "~5.3.0",
    "tslint": "^5.16.0",
    "typescript": "~3.1.6"
  },
  "scripts": {
    "format": "prettier --write --config ../.prettierrc.json 'app/**/*.ts' 'app/**/*.css' 'app/**/*.html'",
    "build.plugin": "cd ../src && npm run build",
    "ci.tslint": "npm run build.plugin && npm i && tslint --config '../tslint.json' 'app/**/*.ts' --exclude '**/node_modules/**'"
  }
}

### Please, tell us how to recreate the issue in as much detail as possible.
Describe the steps to reproduce it.
i Have the  error to run in android File to find module @Nota-exte to find module 
### Is there any code involved?
 - If possible provide an example project demonstrating the issue.
 - Provide a code example to recreate the problem

**Comment by m-abs** [comment]
Hi @enfralys 

Thank you for your bug rapport.
Running the demo isn't documented.

To run the demo from the git-repo, you need go into the `src`-folder and run  `npm run demo.android` or `npm run demo.ios`.

I've added instructions to the readme.

**Comment by enfralys** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @nota/nativescript-webview-ext@5.2.0 build:webview-bridge: `export WWW_OUTDIR=$PWD/www; cd $(git rev-parse --show-toplevel)/www-src && npm i && npm run build -- --outDir ${WWW_OUTDIR}`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @nota/nativescript-webview-ext@5.2.0 build:webview-bridge script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/developer1/.npm/_logs/2019-05-14T14_17_11_250Z-debug.log
ERROR: "build:webview-bridge" exited with 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nota/nativescript-webview-ext@5.2.0 build: `npm ci && rimraf www && npm-run-all build:webview-bridge build:polyfill ngc tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nota/nativescript-webview-ext@5.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/developer1/.npm/_logs/2019-05-14T14_17_11_299Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nota/nativescript-webview-ext@5.2.0 demo.android: `npm run build && npm-run-all demo.install --parallel build:webview-bridge:watch plugin.tscwatch run.demo.android run.http-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @nota/nativescript-webview-ext@5.2.0 demo.android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/developer1/.npm/_logs/2019-05-14T14_17_11_341Z-debug.log

**Comment by bartsg** [comment]
I had the same issue. You have to use git clone. Just downloading the source from github will break the npm script.

**Comment by m-abs** [comment]
Hi @bartsg,

Thank you very much, that explains it.

We use `git rev-parse --show-toplevel` in the build scripts to locate the project root-path for the build scripts.
