### ISSUE TITLE
IOS : Module url resolves to an untyped module

### ISSUE THREAD

**Issue by mfik** [Notalib/nativescript-webview-ext#41]
### Which platform(s) does your issue occur on?
- iOS - Iphone 7 - iOS 12.3

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.0.2
- iOS: Cloud build through sidekick
- nodejs: v10.15.2
- tns-core-modules: 6.0.1
- Runtime(s): iOS 6.0.1
- Plugin(s):

{
  "nativescript": {
    "id": "nl.xxx.xxx",
    "tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.0.1"
    }
  },
  "description": "-",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"src/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "8.0.3",
    "@angular/common": "8.0.3",
    "@angular/compiler": "8.0.3",
    "@angular/core": "8.0.3",
    "@angular/forms": "8.0.3",
    "@angular/http": "8.0.0-beta.10",
    "@angular/platform-browser": "8.0.3",
    "@angular/platform-browser-dynamic": "8.0.3",
    "@angular/router": "8.0.3",
    "@nota/nativescript-webview-ext": "6.0.0-alpha.2",
    "nativescript-angular": "8.0.2",
    "nativescript-appversion": "1.4.2",
    "nativescript-calendar": "2.1.0",
    "nativescript-directions": "1.3.0",
    "nativescript-email": "1.5.4",
    "nativescript-iqkeyboardmanager": "1.5.1",
    "nativescript-mapbox": "4.4.1",
    "nativescript-oauth2": "1.4.3",
    "nativescript-phone": "1.4.0",
    "nativescript-plugin-firebase": "9.0.2",
    "nativescript-theme-core": "1.0.6",
    "nativescript-ui-listview": "7.0.1",
    "nativescript-ui-sidedrawer": "7.0.0",
    "nativescript-web-image-cache": "5.0.0",
    "reflect-metadata": "0.1.13",
    "rxjs": "6.5.2",
    "tns-core-modules": "6.0.1",
    "uglifyjs-webpack-plugin": "2.1.3",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.3",
    "@nativescript/schematics": "0.6.0",
    "@ngtools/webpack": "8.0.6",
    "codelyzer": "5.1.0",
    "nativescript-dev-webpack": "1.0.1",
    "tslint": "5.18.0",
    "tns-platform-declarations": "6.0.1",
    "node-sass": "4.12.0",
    "typescript": "3.4.5"
  },
  "gitHead": "803cec054c44c99eaa59cdc267993e6346f6cb3a",
  "readme": "NativeScript Application",
  "author": "De Software Ontwikkelaar"
}

### Please, tell us how to recreate the issue in as much detail as possible.
Can't build because of missing URL module, which should be global i think?

[19-07-25 17:05:11.839] (CLI) ERROR in node_modules/@nota/nativescript-webview-ext/webview-ext-common.d.ts(120,16): error TS2665: Invalid module name in augmentation. Module 'url' resolves to an untyped module at 'C:/Users/MYNAME/Documents/NativeScriptSidekickApps/APPNAME/node_modules/url/url.js', which cannot be augmented.
node_modules/@nota/nativescript-webview-ext/webview-ext-common.d.ts(121,42): error TS2304: Cannot find name 'Url'.

### Is there any code involved?
import { WebViewExt,ShouldOverrideUrlLoadEventData } from "@nota/nativescript-webview-ext";

viewLoaded(args1) {
        const wv = args1.object;
        wv.on(WebViewExt.shouldOverrideUrlLoadingEvent, (args: ShouldOverrideUrlLoadEventData) => {
            console.log(args.url);
            console.log(args.httpMethod);
        });
    }

<WebView id="articleWebview" [src]="newsItem.content.rendered" (loaded)="viewLoaded"></WebView>

**Comment by m-abs** [comment]
Hi @mfik 

Thank you for reporting the problem.

> Can't build because of missing URL module, which should be global i think?

It complains about typing for this module https://www.npmjs.com/package/url

Are you sure you have `@nota/nativescript-webview-ext@6.0.0-alpha.2` installed? I see it in your `package.json`, but:
The problem should've been solved before `6.0.0-alpha.1` and from what I can see the line number in the output matches `webview-ext-common-d.ts` from `v5.4.1` not `v6.0.0-alpha.2`.

If it's still a problem, you can work around it by installing `@types/node` as a devDependency but it shouldn't be needed anymore.

**Comment by mfik** [comment]
Hi @m-abs,

You where absolutely right. I removed platform, node_modules and the .cloud folder and the error was removed. Thank you!
