### ISSUE TITLE
UIWebview: deprecated API usage ITMS-90809

### ISSUE THREAD

**Issue by bartsg** [Notalib/nativescript-webview-ext#49]
As you may have heard, Apple is sending out warnings to developers regarding the deprecated UIWebView (see: https://forums.developer.apple.com/thread/122114). The exact deadline for this is still unknown.

This means that the plugin shouldn't use the custom NSURLProtocol solution anymore.
Would the URL interceptor still work properly without the WKURLSchemeHandler on iOS < 11?

**Comment by m-abs** [comment]
Hi @bartsg 

Thank you for the heads up.

No, unfortunately the URL interceptor will not work for iOS < 11 without `UIWebView`.

This is pretty worrying as we still need to support older iOS versions in our app.

**Comment by leganz** [comment]
Are there any intentions to remove UIWebView Support so apple won't trigger this notification? I tried to avoid it by choose the app target => 12.0. But it did not work.

**Comment by m-abs** [comment]
@leganz 
Yes, we'll have to remove support for `UIWebView` soon.

Unfortunately that will remove support for iOS <11 for from this plugin, since `UIWebView` is the only way to support the custom schema `x-local://`.

As I understand it, this is still just a warning not an error, so it shouldn't prevent you from publishing.

**Comment by m-abs** [comment]
I've just released v6.2.0 that removes support for `UIWebView`.

The plugin can still be used on iOS < 11, but `x-local://` resources cannot be used by those versions of iOS.

**Comment by Rho-bur** [comment]
Hi @m-abs ,
I am on 
 CLI:  6.5..0
- iOS: XCode version: 11.4
- nodejs: 11.15.0
- tns-core-modules:  6.5.1
- Runtime(s):  6.5.0 both
- Plugin:  6.3.1
And still got this warning after validating and submitting the app to App Store Connect.
It gets accepted with the warning:
"TMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020"
