### ISSUE TITLE
Installation is very unclear

### ISSUE THREAD

**Issue by robtoll** [Notalib/nativescript-webview-ext#59]
Previously I could use this plugin by following the installation instructions, and the support docs.

That was version 5.1.2, and it worked 'out of the box', but now it seems that a simple installation is not enough any more? I think it requires building, but there are no instructions on how to do this.

I tried to run the demo, but I get loads of errors.

Are you able to give me simple installation instructions please? And maybe update your installation guide to include all of the necessary steps?

I only need this on Android.

Hope you can help - thanks

**Comment by m-abs** [comment]
Hi @robtoll 

What kind of errors do you get? 

Is it something like this?
```bash
Execution failed for task ':app:processDebugManifest'.
Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [:webviewinterface:] /Users/b044552/.gradle/caches/transforms-2/files-2.1/50de69abefde0db22b23f83d7e9cdf2f/webviewinterface/AndroidManifest.xml as the library might be using APIs not available in 17
        Suggestion: use a compatible library with a minSdk of at most 17,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="dk.nota.webviewinterface" to force usage (may lead to runtime failures)
```

If so, you need to find your `app.gradle`-file and change `minSdkVersion 17` to `minSdkVersion 19`.

I think that is the only thing we don't document in the `readme`.

**Comment by robtoll** [comment]
Thanks for the reply. I'm up to date with the Typescript CLI.
I'm using MinSKD 19 - targetSDK 20.
The error I'm seeing is...

System.err: Caused by: com.tns.NativeScriptException: Calling js method onCreate failed
System.err: Error: Building UI from XML. @app-root.xml:1:1
System.err:  > Module build failed (from ../node_modules/nativescript-dev-webpack/xml-namespace-loader.js):
System.err:   Error: Unbound namespace prefix: "ns"
System.err: Line: 0
System.err: Column: 125

I'm just using a basic page as per your example, and I have included the reference ns:nota="@nota/nativescript-webview-ext" in the Page tag.

To be honest I'm using a different webview plugin now
https://github.com/shripalsoni04/nativescript-webview-interface
It works fine, so I don't think the problem is with my setup?

Anmyway, hope that info is useful to you.

**Comment by m-abs** [comment]
Sorry, I forgot to respond.

I see the problem.

It should be `xmlns:nota="@nota/nativescript-webview-ext"`not as we've written in the readme `ns:nota="@nota/nativescript-webview-ext"`.

I'll update the README right away, sorry for the inconvience.

**Comment by m-abs** [comment]
REAME updated in `v6.3.1`. Thank you for the bug rapport and sorry for the inconvience.

**Comment by cobreen** [comment]
Changing minSdkVersion to 19 did not fix the problem

Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 19 declared in library [:nativescript_webview_ext:] <path to cache> as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 19,
		or use tools:overrideLibrary="org.nativescript.nativescript_webview_ext" to force usage (may lead to runtime failures)

**Comment by cobreen** [comment]
https://abhiandroid.com/androidstudio/change-api-sdk-level-android-studio.html

Android studio ignores min SDK settings. I changed them using this instruction. Hope it will help somebody
