### ISSUE TITLE
Can't run app after install plugin

### ISSUE THREAD

**Issue by pzdunek** [Notalib/nativescript-webview-ext#6]
Hi I create new project in nativescript sidecick (Typescript + Angular - clean withut anything) and installed your plugin. After auto run (tns run ios) app started  and after 1 sec closing instantly. There are no Exceptions or anything in terminal. I tried to add  WebViewExtModule to @NgModule imports but nothing's happens. 
Please help

**Comment by m-abs** [comment]
Hi,

Thank you for the bug rapport.

I think it might be a timing issue at start up.

We're some javascript for the bridge between `nativescript` and the `webview` in a promise.
If the webview is used before the promise is resolved, it causes a crash on iOS.

A temporary workaround is to use `*ngIf` and a timeout of about 10ms in your component.

**Comment by m-abs** [comment]
This would be solved in the latest version of the plugin.
