### ISSUE TITLE
Can this extension access the webpage DOM?

### ISSUE THREAD

**Issue by erjdriver** [Notalib/nativescript-webview-ext#63]
Will this extension allow me to access a website and acess it's DOM.

Also submit POST and initiate GET operations.

Basically - emulate a user interactive session.

Thanks.

**Comment by m-abs** [comment]
If you can do it by running JavaScript in the webpage, yes.

**Comment by erjdriver** [comment]
I thank you for the extension and will try it out.

The `demo` app could really use some documentation.

Not very clear - also looks like a local webserver is required.

It will also be more helpful if you hosted a web-page and the demo
could access it.

Some DOM manipulation - would be useful.

**Comment by m-abs** [comment]
The demo needs to be started via the npm-scripts in the `src`-folder, this is needed to build the bridge and launch the web-server.

Use `npm run demo.android` or `npm run demo.ios`.
