### ISSUE TITLE
Invalid Tag Name

### ISSUE THREAD

**Issue by artydev** [Notalib/nativescript-webview-ext#68]
Hello,

Thanks for your work.
After having install the plugin and run the sample on an Hello World  Core Template

<Page class="page" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:nota="@nota/nativescript-webview-ext">
    <ActionBar class="action-bar">
        <Label class="action-bar-title" text="Homddde"></Label>
    </ActionBar>

      <nota:WebViewExt src="https://nota.dk"></<nota:WebViewExt>
</Page>

I got the error Invalid tagname in closing tag

Thank you for your Help

regards

**Comment by m-abs** [comment]
Did you add the `xmlns:nota` to the Page-tag?

See: https://github.com/Notalib/nativescript-webview-ext#core-support

**Comment by artydev** [comment]
Thank you for your response.
Yes, i have  copied the sample you give on you site...
It's strange...
I am trying again...

**Comment by artydev** [comment]
When I run your demo, no luck too :


WARNING in ./main-page.xml 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
> <Page
|   xmlns="http://schemas.nativescript.org/tns.xsd" loaded="pageLoaded" class="page"
|   xmlns:nota="@nota/nativescript-webview-ext">
 @ \b_[\w-]*\.)scss)$ (. sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$) ./main-page.xml
 @ ./app.ts

ERROR in C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
Module build failed (from ../node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts.
    at makeSourceMapAndFinish (C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\demo\node_modules\ts-loader\dist\index.js:78:15)
    at successLoader (C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\demo\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\demo\node_modules\ts-loader\dist\index.js:22:12)
 @ ./main-page.ts 4:33-74
 @ . sync (?<!\bApp_Resources\b.*)(?<!\.\/\btests\b\/.*?)\.(xml|css|js|kt|(?<!\.d\.)ts|(?<!\b_[\w-]*\.)scss)$
 @ ./app.ts

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext-common.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext-common.ts(7,81)
      TS2307: Cannot find module './nativescript-webview-bridge-loader'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(129,59)
      TS2345: Argument of type 'WebResourceRequest' is not assignable to parameter of type 'string'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(142,59)
      TS2345: Argument of type 'WebResourceRequest' is not assignable to parameter of type 'string'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(146,59)
      TS2345: Argument of type 'WebResourceRequest' is not assignable to parameter of type 'string'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(153,59)
      TS2345: Argument of type 'WebResourceRequest' is not assignable to parameter of type 'string'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(159,59)
      TS2345: Argument of type 'WebResourceRequest' is not assignable to parameter of type 'string'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(173,68)
      TS2339: Property 'getResponseHeaders' does not exist on type 'WebResourceResponse'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(177,44)
      TS2339: Property 'getResponseHeaders' does not exist on type 'WebResourceResponse'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(183,22)
      TS2339: Property 'setResponseHeaders' does not exist on type 'WebResourceResponse'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(226,13)
      TS2554: Expected 4 arguments, but got 3.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(499,22)
      TS2339: Property 'setMixedContentMode' does not exist on type 'WebSettings'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(499,69)
      TS2339: Property 'MIXED_CONTENT_COMPATIBILITY_MODE' does not exist on type 'typeof WebSettings'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(689,28)
      TS2339: Property 'evaluateJavascript' does not exist on type 'AndroidWebView'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(736,45)
      TS2339: Property 'zoomBy' does not exist on type 'AndroidWebView'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(747,32)
      TS2339: Property 'setWebContentsDebuggingEnabled' does not exist on type 'typeof WebView'.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(798,36)
      TS2569: Type 'Map<CacheMode, number>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts
C:/Users/sdidio-ccrf/Downloads/nativescript-webview-ext-master/nativescript-webview-ext-master/src/webview-ext.ts
[tsl] ERROR in C:\Users\sdidio-ccrf\Downloads\nativescript-webview-ext-master\nativescript-webview-ext-master\src\webview-ext.ts(814,42)
      TS2569: Type 'Map<CacheMode, number>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.

**Comment by m-abs** [comment]
The demo needs to be started from the `src`-folder via the `npm run demo.ios` or `npm run demo.android` scripts.

I don't use `NativeScript core` very much.
But if you could make a demo project so I could see the code, it might be easier for me to help.

**Comment by gaspachoandalus** [comment]
There's an extra "<" on the closing tag in the sample :
`</<nota:WebViewExt>`
