### ISSUE TITLE
Cannot launch the demo app 

### ISSUE THREAD

**Issue by christopharus** [Notalib/nativescript-webview-ext#75]
tns --version :
6.4.1

npm --version: 
6.13.7

I have just cloned the project and launch it and then I get these errors : 

![Screenshot (66)_LI](https://user-images.githubusercontent.com/47279703/80484875-f5ef3780-8947-11ea-97b7-f8c8d1676061.jpg)

**Comment by m-abs** [comment]
Looks like an old problem.

Try doing a `git clean -d -x -f` from the root folder of the project, and launching the demo app from the src folder via `npm run demo.android`/ `npm run demo.ios`.
