### ISSUE TITLE
Chromium logging

### ISSUE THREAD

**Issue by erjdriver** [Notalib/nativescript-webview-ext#76]
Does this plugin enable Chromium logging?

I see a lot of messages like

`chromium: [INFO:library_loader_hooks.cc(50)] Chromium logging enabled: level = 0, default verbosity = 0`

If so - how can I disable or control it.

Thank you.

**Comment by m-abs** [comment]
> Does this plugin enable Chromium logging?

Not by choice. I don't know if we can control it. 

You can listen for console.log on android with the `webConsole` event, but I don't think that will help you here.
