### ISSUE TITLE
Latest Plugin version - 6.5.2 is using UIWebView class which is depracated

### ISSUE THREAD

**Issue by llpl** [Notalib/nativescript-webview-ext#77]
@nota/nativescript-webview-ext             │ ^6.5.2  

Is used in the pure native script project. When we submit the app for review in app store following message is shown :
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
Followinf files has reference to UIWebView
node_modules/@nstudio/nativescript-pulltorefresh/pulltorefresh.ios.js
node_modules/@nota/nativescript-webview-ext/www/ns-webview-bridge.js
node_modules/@nota/nativescript-webview-ext/nativescript-webview-bridge-loader.js

This needs to be fixed to submite app to app store.

**Comment by m-abs** [comment]
*sic* UIWebView is only mentioned in a comment and a log statement.

It has been removed in v6.5.3
