### ISSUE TITLE
Scrolling not working in iOS 12.0.1

### ISSUE THREAD

**Issue by singhsaban** [Notalib/nativescript-webview-ext#8]
Hi,
I've recently upgraded from iOS 12 to 12.0.1 and scrolling in the webview isn't working. My template is as follows.

`<GridLayout rows="*" columns="*">
                  <WebViewExt row="0" col="0" src="..." @loaded="webviewLoaded" debugMode="false"></WebViewExt>
              </GridLayout>`

Scrolling is working fine in iOS 12.0.

As a workaround I tried using a StackLayout and wrapped in with a ScrollView as discussed in [https://github.com/NativeScript/NativeScript/issues/224](https://github.com/NativeScript/NativeScript/issues/224)

`  <ScrollView>
              <StackLayout>
                  <WebViewExt minHeight="1000" src="..." @loaded="webviewLoaded" debugMode="false"></WebViewExt>
              </StackLayout>
          </ScrollView>`

This didn't work either. 

However, it does work if I use the default WebView.

`  <ScrollView>
              <StackLayout>
                  <WebView minHeight="1000" src="..."></WebView>
              </StackLayout>
          </ScrollView>`

**Comment by singhsaban** [comment]
My apologies. The issue was with iOS 12.0.1. After upgrading to iOS 12.1 its scrolling correctly.

**Comment by m-abs** [comment]
Couldn't reproduce and if it works on 12.1, I'll consider this issue closed.

**Comment by singhsaban** [comment]
Scrolling not working for me also. I'm on iOS 12.1.1 (iPhone X). I noticed that scrolling has been turned off in nativescript-webview-ext/webview-ext.uiwebview.js.
> uiWebView.scrollView.scrollEnabled = false;

And setting this to true does fix the issue. Let me know if this is a valid fix for the issue. I could send in a PR.

Thanks.
