### ISSUE TITLE
Missing events from webview

### ISSUE THREAD

**Issue by ray007** [Notalib/nativescript-webview-ext#80]
### Missing events
Event handlers for `titleChanged` and `shouldOverrideUrlLoading` do not get called.

### Which platform(s) does your issue occur on?
- Android/Vue, not yet tested with iOS
- Android 9 on Samsung Galaxy S8+

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.7.4
- nodejs: v12.18.0
- tns-core-modules: 6.5.2
- Runtime(s): 6.5.1
- Plugin(s): 
```json
  "dependencies": {                                
    "@nativescript/theme": "~2.3.3",               
    "@nota/nativescript-webview-ext": "^6.5.3",    
    "nativescript-bluetooth": "^3.0.0-beta.10",    
    "nativescript-inappbrowser": "^2.3.0",         
    "nativescript-vue": "~2.5.0",                  
    "node-forge": "^0.9.1",                        
    "tns-core-modules": "^6.5.2",                  
    "url-parse": "^1.4.7"                          
  },                                               
  "devDependencies": {                             
    "@babel/core": "~7.1.0",                       
    "@babel/preset-env": "~7.1.0",                 
    "babel-loader": "~8.0.0",                      
    "nativescript-dev-webpack": "~1.5.1",          
    "nativescript-vue-template-compiler": "~2.5.0",
    "node-sass": "^4.7.1",                         
    "vue-loader": "~15.9.0",                       
    "typescript": "3.4.5"                          
  },                                               
```

### Please, tell us how to recreate the issue in as much detail as possible.
In `app.js` I have
```
import * as wvx from "@nota/nativescript-webview-ext/vue";
```

And in the vue-component:
```<WebViewExt ref="wvx" :src="url" v-bind="wvxProps" v-on="wvxEv"/>```

I'm setting `wvxProps` and `wvxEv` in the component's `created` handler:
```javascript
		this.wvxEv = {
			loadStarted: ev => {
				console.log('load started');
			},
			loadFinished: ev => {
				console.log('load finished');
			},
			titleChanged: title => {
				console.log('title', title);
			},
			shouldOverrideUrlLoading: (url, arg) => {
				console.log('url ovr', url, arg);
			}
		};
```
The handlers for `loadStarted` and `loadFinished` get called, the other 2 do not.
Haven't yet tested with the remaining documented events.
I know that the document title get changed since I checked with `getTitle()` in the `loadFinished` handler, and I know that http requests get made since I see their result displayed in the webview.

I also tried to go with
```javascript
this.$refs.wvx.nativeView.on('titleChanged', ...);
```
but no luck with that either.

Any idea what I'm doing wrong?

**Comment by ray007** [comment]
Update: I'm getting the `shouldOverrideUrlLoading` when loading a local html/js app, through I have no idea where `args.cancel` would be found. And I guess it's only for dealing with the frame loading url, not `XmlHttpRequest`s made from the js app?
Still no `titleChanged` event.

**Comment by m-abs** [comment]
Hmmm, looks like a bug with the native webview...

**Comment by keithoys** [comment]
titleChanged does not get called on iOS too. I'm on "@nota/nativescript-webview-ext": "^6.5.5".
