### ISSUE TITLE
ns-bridge-ready is not working in iOS

### ISSUE THREAD

**Issue by phoenix503** [Notalib/nativescript-webview-ext#86]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
I am trying to send data from nativeapp to webview(angular webview) but the event "ns-bridge-ready" is not working in iOS rather than if i remove ns-bridge-ready , the inside function works fine but then this becomes undefined in Android

### Which platform(s) does your issue occur on?
- iOS
- iOS : 13.5
- emulator or device. : iphone 11 simulator

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.7.4

### Please, tell us how to recreate the issue in as much detail as possible.
I am running the code inside the Ng-library which talks with the NS-app

### Is there any code involved?

  

window.addEventListener("ns-bridge-ready", (e) => {
window.nsWebViewBridge.on("NativeToWeb",  (data) => {
                // do stuff here
          });
     });

**Comment by gusev-genotek** [comment]
@phoenix503 why is this issue closed? Did you find a fix to a problem? Which one? Thanks
