### ISSUE TITLE
WebView version stucked at iOS App Release: AppStore

### ISSUE THREAD

**Issue by phoenix503** [Notalib/nativescript-webview-ext#91]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS
- iOS : 11
- emulator or device. Emulator 

### Please, tell us how to recreate the issue in as much detail as possible.
Describe the steps to reproduce it.
I am getting this error whenever i am trying to update my app over Appstore

_ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview)._

Even though i am using latest Notalib webView 6.5.4. The error started coming to me after 17th Aug 2020 before the app which i have submitted it is working fine.

### Is there any code involved?
No

**Comment by phoenix503** [comment]
Hi @m-abs , I am able to solved this issue my overriding the Podfile of **AFNetworking**
You can do it or advise others to do so with latest version 4.0
https://github.com/AFNetworking/AFNetworking

**Comment by m-abs** [comment]
Thank you for the tip, I'll redirect others to it :)
