### ISSUE TITLE
Link that opens a pdf file not getting loaded

### ISSUE THREAD

**Issue by erjdriver** [Notalib/nativescript-webview-ext#92]
Using the latest version of the plugin.

I've got a web-page with a simple link to a pdf file

`<a href="test.pdf">file</a>`

When I click on the link - nothing happens. I'm trying to get the pdf file opened.

I get the `shouldOverrideUrlLoadingEvent` event for the .pdf url - but never the `loadFinishedEvent` event.

So nothing happens after clicking on the link.

I don't need to process the page (or need `loadFinishedEvent` called) - I would just like the pdf file to be opened.

Any help?

**Comment by Bezlepkin** [comment]
> Using the latest version of the plugin.
> 
> I've got a web-page with a simple link to a pdf file
> 
> `<a href="test.pdf">file</a>`
> 
> When I click on the link - nothing happens. I'm trying to get the pdf file opened.
> 
> I get the `shouldOverrideUrlLoadingEvent` event for the .pdf url - but never the `loadFinishedEvent` event.
> 
> So nothing happens after clicking on the link.
> 
> I don't need to process the page (or need `loadFinishedEvent` called) - I would just like the pdf file to be opened.
> 
> Any help?

Have you solved this problem?
