### ISSUE TITLE
tns version 7.0.8 ios breaks WebViewExt 6.5.4 

### ISSUE THREAD

**Issue by minskmaz** [Notalib/nativescript-webview-ext#93]
Hi I've been using WebViewExt for about a year. It's really powerful for my needs. However this latest {NS} update has broken something and I'm uncertain how to proceed.

### Which platform(s) does your issue occur on?
- iOS

### Please, provide the following version numbers that your issue occurs with:

tns             7.0.8               
xcode           Xcode 11.7 Build version 11E801a
node            v12.18.3            
core            tns-core-modules@6.5.18
dependencies    {
  "@nativescript/core": "~7.0.0",
  "@nativescript/theme": "~2.3.0",
  "@nota/nativescript-webview-ext": "^6.5.4",
  "nativescript-geolocation": "^5.1.0",
  "nativescript-ios-uuid": "^1.0.0",
  "nativescript-secure-storage": "^2.6.2",
  "nativescript-websockets": "^1.5.5"
}
devDependencies {
  "@nativescript/ios": "7.0.0",
  "@nativescript/webpack": "~3.0.0",
  "nativescript-dev-typescript": "^0.10.0",
  "nativescript-worker-loader": "^0.11.1-next-2020-02-20-102900-01"
}

### Please, tell us how to recreate the issue in as much detail as possible.

Using your most basic example (below) with a vanilla js {NS} project 

`
<Page class="page" xmlns="http://schemas.nativescript.org/tns.xsd" xmlns:nota="@nota/nativescript-webview-ext">
    <ActionBar class="action-bar">
        <Label class="action-bar-title" text="Home"></Label>
    </ActionBar>
    <nota:WebViewExt src="https://nota.dk"></nota:WebViewExt>
</Page>
`

I get this error:

*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught Error: Building UI from XML. @app-root.xml:1:1
> Building UI from XML. @main-page.xml:5:5
> Module '@nota/nativescript-webview-ext' not found for element '@nota/nativescript-webview-ext:WebViewExt'.
> Class constructor ContainerView cannot be invoked without 'new'
at
ScopeError(file: node_modules/@nativescript/core/utils/debug.js:51:0)
at SourceError(file: node_modules/@nativescript/core/utils/debug.js:58:0)
at (file: node_modules/@nativescript/core/ui/builder/index.js:228:0)
at (file: node_modules/@nativescript/core/ui/builder/index.js:207:0)
at (file: node_modules/@nativescript/core/xml/index.js:412:0)
at push.../node_modules/@nativescript/core/js-libs/easysax/easysax.js.EasySAXParser.parse(file: node_modules/@nativescript/core/js-libs/easysax/easysax.js:751:0)
at parse(file: node_modules/@nativescript/core/xml/index.js:455:0)
at parse(file: node_modules/@nativescript/core/ui/builder/index.js:213:0)
at parseInternal(file: node_modules/@nativescript/core/ui/builder/index.js:181:0)
at loadInternal(file: node_modules/@nativescript/core/ui/builder/index.js:94:0)
at createViewFromEntry(file: node_modules/@nativescript/core/ui/builder/index.js:36:0)
at createRootView(file: node_modules/@nativescript/core/application/index.ios.js:312:30)
at setWindowContent(file://<\M-b\M^@\M-&>
Initializing connection
Removing all cached process handles
Sending handshake request attempt #1 to server
Creating connection to com.apple.runningboard
Handshake succeeded
Identity resolved as application<org.nativescript.dappwrapp>
Successfully run application org.nativescript.dappwrapp on device with ID 57643e7a3bc0015c11ffd8e923f82ab356ac0146.
CONSOLE INFO: HMR: Hot Module Replacement Enabled. Waiting for signal.
[FBSDisplaySource 1-1] silently connecting <FBSDisplayConfiguration: 0x280ca81c0; Main; mode: "414x736@3x 60Hz p3 SDR">
[FBSDisplaySource 1-1] initialized <FBSDisplayConfiguration: 0x280ca81c0; Main; mode: "414x736@3x 60Hz p3 SDR">
NativeScript debugger has opened inspector socket on port 18183 for org.nativescript.dappwrapp.
FBSWorkspace connecting to endpoint : <private>
FBSWorkspace registering source: <private>
FBSWorkspace connected to endpoint : <private>
Added observer for process assertions expiration warning: <_RBSExpirationWarningAssertion: 0x282087e80; identifier: com.apple.runningboardservices.processExpirationWarningForHandle; reason: observation; valid: YES>
Retrieving resting unlock: 0
Registering for test daemon availability notify post.
notify_get_state check indicated test daemon not ready.
FBSWorkspace already connected to endpoint : <private>

### Is there any code involved?

No (given above)

**Comment by m-abs** [comment]
Thank you for reporting this.

I'm on vacation this week, but will look into upgrading this plugin to NS7.

**Comment by minskmaz** [comment]
Enjoy!

**Comment by FlawaCLV** [comment]
Thanks @m-abs !

Indeed, NS7 migrated from `tns-core-modules` to `@nativescript/core`.

**Comment by m-abs** [comment]
I just published v7.0.0, can you test if it solves to problem?

**Comment by minskmaz** [comment]
Thanks @m-abs will test sometime after 5pm PST.

**Comment by phoenix503** [comment]
Hi @m-abs  , 
I am facing this issue while building in webview v7.0.0
**"command phasescriptexecution failed with a nonzero exit code"**

Can you please tell about it. All conditions are normal, it is working fine before just i have updated the noteLib-webview-ext

and 

"tns-ios": {
      "version": "6.5.3"
    },
    "tns-android": {
      "version": "6.5.3"
    }

**Comment by m-abs** [comment]
@phoenix503 
v7.0+ requires tns-ios/tns-android 7+. If you're still on tns-ios/tns-android v6.5.x, you need v.6.5.x of the plugin.
